### ISSUE TITLE
Error `InitPlugins()`

### ISSUE THREAD

**Issue by wendyliga** [Ryzhehvost/ASF-Achievement-Manager#19]
run the plugin on asf 5.2.1.4 docker
any idea?

error detail 
```
2021-12-28 07:27:36|dotnet-19|ERROR|ASF|InitPlugins() Failed due to error: ASF-Achievement-Manager, Version=0.2.0.0, Culture=neutral, PublicKeyToken=null
2021-12-28 07:27:36|dotnet-19|ERROR|ASF|InitPlugins() System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'OnBotSteamCallbacksInit' in type 'ASFAchievementManager.ASFAchievementManager' from assembly 'ASF-Achievement-Manager, Version=0.2.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
System.TypeLoadException: Method 'OnBotSteamCallbacksInit' in type 'ASFAchievementManager.ASFAchievementManager' from assembly 'ASF-Achievement-Manager, Version=0.2.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

**Comment by wendyliga** [comment]
i think, the culprit maybe because start from ASF 5.2.0.10, you need to use net 6.0

**Comment by Ryzhehvost** [comment]
This is because plugin is for current stable verstion of ASF, and you are using a pre-release. But if you don't want to wait - you can build plugin from source and use it with pre-release, since changes in the code already made.

**Comment by wendyliga** [comment]
ok got it work with 5.1.2.4, thank you

**Comment by Gaffi** [comment]
5.1.2.5 is now stable release, and I am now seeing this issue.
