### ISSUE TITLE
Error starting

### ISSUE THREAD

**Issue by CrazyGhostRider** [Ryzhehvost/ASF-Achievement-Manager#20]
2022-03-04 12:44:42|ArchiSteamFarm-3780|ERROR|ASF|InitPlugins() ASF-Achievement-Manager, Version=0.2.1.0, Culture=neutral, PublicKeyToken=null
2022-03-04 12:44:42|ArchiSteamFarm-3780|ERROR|ASF|InitPlugins() System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule )
   at System.Reflection.RuntimeModule.GetTypes()
   at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
System.TypeLoadException

ASF v5.2.3.6

**Comment by woctezuma** [comment]
See:
- https://github.com/Ryzhehvost/BoosterCreator/issues/11

**Comment by woctezuma** [comment]
Fixed by #21, I guess.
