### ISSUE TITLE
Error Starting Plugin

### ISSUE THREAD

**Issue by zLuca028** [Ryzhehvost/ASF-Achievement-Manager#22]
2022-03-05 16:23:01|ArchiSteamFarm-1116|INFO|ASF|InitCore() ArchiSteamFarm V5.2.3.6 (win-x64/0642cde5-d88b-4e92-9aea-a57304046775 | .NET 6.0.2; win10-x64; Microsoft Windows 10.0.22000)
2022-03-05 16:23:01|ArchiSteamFarm-1116|INFO|ASF|InitCore() Copyright © 2015-2022 JustArchiNET
2022-03-05 16:23:01|ArchiSteamFarm-1116|INFO|ASF|InitPlugins() Inizializzazione di Plugins in corso...
2022-03-05 16:23:01|ArchiSteamFarm-1116|ERROR|ASF|InitPlugins() Fallito a causa di un errore: ASF-Achievement-Manager, Version=0.2.1.0, Culture=neutral, PublicKeyToken=null
2022-03-05 16:23:01|ArchiSteamFarm-1116|ERROR|ASF|InitPlugins() System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule )
   at System.Reflection.RuntimeModule.GetTypes()
   at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
System.TypeLoadException

ASF  V5.2.3.6

**Comment by woctezuma** [comment]
- https://github.com/Ryzhehvost/ASF-Achievement-Manager/issues/20
